M48
; DRILL file {KiCad 7.0.8} date Thu Oct 19 22:15:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-19T22:15:17-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X3.0566Y-3.6
X3.1Y-3.8
X3.2Y-4.0
X3.8Y-3.0
X3.8Y-3.7
T2
X3.7016Y-2.9
X3.8Y-2.9
T0
M30
